issue 12 possible fix
cloudposse/terraform-aws-sso pull request #13
Opened 2021-05-17 16:30 UTC by innominatus

## what
* a.permission_set_arn is providing a unique value to the account_assignment name.
* However the permission_set_arn can not be determined until after the apply of the permission sets.
* Using a.permission_set_arn in account_assignments before the permission sets have been applied will result in the following error.

```
Error: Invalid for_each argument

  on .terraform/modules/sso_account_assignments/modules/account-assignments/main.tf line 30, in resource "aws_ssoadmin_account_assignment" "this":
  30:   for_each = local.assignment_map

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

## why
* Attempting to provide a unique (enough) value that is already predetermined before apply by adding a.permission_set_name instead of arn.
```
  account_assignments = [
    {
        account = "111111111111",
        permission_set_name = "administratoraccess",
        permission_set_arn = "arn:aws:sso:::permissionSet/ssoins-0000000000000000/ps-31d20e5987f0ce66",
        principal_type = "GROUP",
        principal_name = "Administrators"
    },
```
* Yes, its less unique but there should be only one assignment using the same account, principal, principal type, and permission set name.
* Yes, you are carrying 2 values over from the permission set (name and arn) instead of just one (arn). But it gets around the uniqueness problem. I couldnt think of any other good choice at the moment. Maybe someone else will come up with a better value. Maybe use a random_string.name.result?

## references
* `Issue #12`

2021-05-18 08:36 UTC, jgrumboe commented on modules/account-assignments/variables.tf
>      principal_type     = string
```suggestion
    account             = string
    permission_set_name = string
    permission_set_arn  = string
    principal_name      = string
    principal_type      = string
```
Just added spaces to fulfill linting.

2021-05-19 15:36 UTC, nicolaevladescu commented
I have been successful with a workaround that does not involve another arbitrary key, i have opened a PR, can you guys check it out? #14

2021-05-20 11:35 UTC, jgrumboe commented
I'm happy with this solution. Although it's a new arbitrary key, you can see it as a description or comment of the assignment and it helps to have stable resource names which avoid unnecessary recreation of resources when the list is altered.
That's a big benefit for me.

2021-06-04 23:25 UTC, aknysh commented
/terraform-fmt

2021-06-04 23:34 UTC, aknysh commented
/test all

2021-06-07 21:26 UTC, nitrocode commented
/test all

2021-06-07 21:40 UTC, nitrocode commented
/test all

2021-06-07 21:53 UTC, jgrumboe commented
I think `test all` is simply not applicable in this repo.

2021-06-07 21:53 UTC, jgrumboe commented
/test

2021-06-10 18:26 UTC, Nuru requested changes, later dismissed

2021-06-10 18:26 UTC, Nuru commented on modules/account-assignments/main.tf
> +      format("%v%v%v", a.principal_name, a.principal_type, a.permission_set_name)
OK, If we are going to require a permission set name, let's make the label readable:
```
for a in var.account_assignments : format("%v-%v-%v-%v", a.account, substr(a.principal_type, 0, 1), a.principal_name, a.permission_set_name)
```

2021-06-11 01:26 UTC, Nuru approved these changes

2021-06-11 01:55 UTC, merged

2021-06-11 04:58 UTC, jgrumboe commented
🎉