Fix AWS provider 4.40 deprecation warnings
cloudposse/terraform-aws-sso pull request #35
Opened 2022-12-20 11:57 UTC by simonweil

## what
Fix the deprecation warnings as described here: https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.40.0

## why
Otherwise there are deprecation warnings...

## references
* https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.40.0
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/identitystore_group#filter
* closes #34

2023-01-24 01:18 UTC, purduemike commented
Can someone approve this PR?

2023-01-24 02:15 UTC, aknysh requested changes
@simonweil please see comments in https://github.com/cloudposse/terraform-aws-sso/pull/33#pullrequestreview-1266706283

thanks for the PRs

2023-03-09 12:09 UTC, simonweil commented
@aknysh PR updated with the last changes to master, it's ready for merge from my point of view.
Let's go? :)

2023-03-13 14:06 UTC, aknysh approved these changes

2023-03-13 14:06 UTC, aknysh commented
/test all

2023-03-13 14:14 UTC, merged

2023-03-13 16:09 UTC, simonweil commented
Thanks for merging!